---
- name: Sync Cathexis User Database
  hosts: other_servers
  become: false 
  vars:
    db_path: "/home/ubuntu/nvr/users.db"
  tasks:

    - name: Ensure sqlite3 is installed
      package:
        name: sqlite3
        state: present

    - name: Check if Users and Password tables exist
      command: sqlite3 "{{ db_path }}" "SELECT name FROM sqlite_master WHERE type='table' AND (name='users' OR name='passwords');"
      register: db_checksqlite3
      changed_when: false
      failed_when: false

    - name: Copy data if doesn't exist
      when: "'users' not in db_checksqlite3.stdout"
      synchronize:
        src: "{{ db_path }}"
        dest: "{{ db_path }}"
        mode: push
      delegate_to: gittest

- name: Copy master database from gittest
  hosts: other_servers
  become: no
  tasks:
    - name: Rsync users.db from gittest
      command: rsync -avz ubuntu@172.31.17.101:/home/ubuntu/nvr/users.db /home/ubuntu/nvr/users_master.db

- name: Sync users from gittest to server1 and server2
  hosts: other_servers
  become: yes
  vars:
    sh_path: "/home/ubuntu/nvr/sync.py"
    local_db: "/home/ubuntu/nvr/users.db"
    master_db: "/home/ubuntu/nvr/users_master.db"
  tasks:

    - name: Copy multiple scripts to remote machine
      copy:
        src: "{{ item }}"
        dest: "/home/ubuntu/nvr/{{ item | basename }}"
        mode: '0777'
      with_items:
        - /home/ubuntu/userdb/sync.py
        - /home/ubuntu/userdb/password.py

    - name: Execute script to compare local vs master database
      command: python3 {{ sh_path }} "{{ local_db }}" "{{ master_db }}"
      register: script_output

    - name: script output  
      debug:
        var: script_output

- name: Password sync serv 1
  hosts: main
  become: no
  vars:
    sh_path: "/home/ubuntu/userdb/password.py"
    local_db: "/home/ubuntu/nvr/users.db"
    master_db: "/home/ubuntu/nvr/users_sev1.db"
  tasks:

    - name: Rsync users.db from gittest
      command: rsync -avz ubuntu@172.31.23.120:/home/ubuntu/nvr/users.db /home/ubuntu/nvr/users_sev1.db

    - name: Execute script to compare local vs master database
      command: python3 {{ sh_path }} "{{ master_db }}"
      register: password_output
    
    - name: password output  
      debug:
        var: password_output

