---
- name: Sync Cathexis User Database
  hosts: other_servers
  become: false
  vars:
    db_path: "/usr/nvr/unitconfig/db/users.db"
  tasks:
    - name: Ensure sqlite3 is installed
      apt:
        name: sqlite3
        state: present

    - name: Check if Users and Password tables exist
      command: sqlite3 "{{ db_path }}" "SELECT name FROM sqlite_master WHERE type='table' AND (name='users' OR name='passwords');"
      register: db_checksqlite3
      changed_when: false
      failed_when: false

    - name: Copy data if doesn't exist
      when: "'users' not in db_checksqlite3.stdout"
      synchronize:
        src: "{{ db_path }}"
        dest: "{{ db_path }}"
        mode: push
      delegate_to: CARA-MAIN 

- name: Copy any dependancies
  hosts: other_servers
  become: false
  tasks:
    - name: Synchronize users.db from main server
      synchronize:
        src: /usr/nvr/unitconfig/db/users.db
        dest: /usr/nvr/unitconfig/db/users_master.db
        mode: pull
        private_key: "~/.ssh/ansible_id_rsa"
        ssh_args: "-o StrictHostKeyChecking=no"

    - name: Copy multiple scripts to remote machine
      copy:
        src: "{{ item }}"
        dest: "/usr/nvr/{{ item | basename }}"
        mode: '0777'
      with_items:
        - /home/cctvadmin/userdb/password.py
        - /home/cctvadmin/userdb/sync.py

- name: Sync users from gittest to server1 and server2
  hosts: other_servers
  become: false
  vars:
    sync_path: "/usr/nvr/sync.py"
    local_db: "/usr/nvr/unitconfig/db/users.db"
    master_db: "/usr/nvr/unitconfig/db/users_master.db"
  tasks:
    - name: Execute script to compare local vs master database
      command: python3 {{ sync_path }} "{{ local_db }}" "{{ master_db }}"
      register: script_output

    - name: script output  
      debug:
        var: script_output

- name: Password sync serv 1
  hosts: main
  become: false
  vars:
    sh_path: "/home/cctvadmin/userdb/password.py"
    local_db: "/usr/nvr/unitconfig/db/users.db"
    sev_1: "/usr/nvr/unitconfig/db/users_sev1.db"
    sev_2: "/usr/nvr/unitconfig/db/users_sev2.db"
  tasks:
    - name: Synchronize passwords from server1
      synchronize:
        src: /usr/nvr/unitconfig/db/users.db
        dest: /usr/nvr/unitconfig/db/users_sev1.db
        mode: pull
        private_key: "~/.ssh/ansible_id_rsa"
        ssh_args: "-o StrictHostKeyChecking=no"

    - name: Execute script to compare local vs master database
      command: python3 {{ sh_path }} "{{ local_db }}" "{{ sev_1 }}"
      register: password_output
    
    - name: password output  
      debug:
        var: password_output 

    # - name: Rsync passwords from sev2
    #   command: rsync -avz ubuntu@172.31.31.144:/home/ubuntu/nvr/users.db /home/ubuntu/nvr/users_sev2.db

    # - name: Execute script to compare local vs master database
    #   command: python3 {{ sh_path }} "{{ local_db }}" "{{ sev_2 }}"
    #   register: password_output2

    # - name: password output  
    #   debug:
    #     var: password_output2 
