---
- name: Sync Cathexis User Database
  hosts: other_servers
  become: false 
  vars:
    db_path: "/home/ubuntu/nvr/users.db"
  tasks:

    - name: Ensure sqlite3 is installed
      package:
        name: sqlite3
        state: present

    - name: Check if Users and Password tables exist
      command: sqlite3 "{{ db_path }}" "SELECT name FROM sqlite_master WHERE type='table' AND (name='users' OR name='passwords');"
      register: db_checksqlite3
      changed_when: false
      failed_when: false

    - name: Copy data if doesn't exist
      when: "'users' not in db_checksqlite3.stdout"
      synchronize:
        src: "{{ db_path }}"
        dest: "{{ db_path }}"
        mode: push
      delegate_to: gittest

- name: Sync users from gittest to server1 and server2
  hosts: all
  become: yes
  vars:
    db_path: "/home/ubuntu/nvr"
  tasks:

    - name: Copy Script 
      ansible.builtin.copy:
        src: sync.py
        dest: /home/ubuntu/nvr/sync.py
        mode: '0777'
      delegate_to: gittest 